version: '2'

services:

  web: &web
    build: .
    environment:
      VIRTUAL_HOST: decryptonomicon.*
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  webpack:
    <<: *web
    command: npm run webpack-watch

volumes:
  node_modules:
    driver: local
